version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: event-platform-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data-dev:/data/db
    networks:
      - event-platform-network

networks:
  event-platform-network:
    driver: bridge

volumes:
  mongo-data-dev: