apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: event-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: smart-event-platform-booking-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4003
        env:
        - name: PORT
          value: "4003"
        - name: MONGO_URI
          value: mongodb://admin:password@mongodb-service:27017/bookings?authSource=admin
        - name: AUTH_SERVICE_URL
          value: http://auth-service:4001
        - name: EVENT_SERVICE_URL
          value: http://event-service:4002
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: event-platform
spec:
  selector:
    app: booking-service
  ports:
  - port: 4003
    targetPort: 4003
  type: ClusterIP