name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-services:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Test auth-service
        working-directory: ./services/auth-service
        run: |
          npm ci
          npm test
      
      - name: Test event-service
        working-directory: ./services/event-service
        run: |
          npm ci
          npm test
      
      - name: Test booking-service
        working-directory: ./services/booking-service
        run: |
          npm ci
          npm test

  build-check:
    runs-on: ubuntu-latest
    needs: [test-services]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth-service
          push: false
      
      - name: Build event-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/event-service
          push: false
      
      - name: Build booking-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/booking-service
          push: false















