name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Check code formatting
        run: |
          echo "Checking code quality..."
          find services -name "*.js" | head -5
      
      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}

  docker-build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Test Docker build - auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth-service
          push: false
          tags: event-platform-auth:test
      
      - name: Test Docker build - event-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/event-service
          push: false
          tags: event-platform-event:test
      
      - name: Test Docker build - booking-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/booking-service
          push: false
          tags: event-platform-booking:test

  pr-comment:
    runs-on: ubuntu-latest
    needs: [code-quality, docker-build-test]
    
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ All checks passed! Ready for review.'
            })